const Color = {
  BACKGROUND_COLOR: '#F6E8D8',
  BUTTON_COLOR: '#ABCEEA',
  BORDER_COLOR: '#888888',
  FIRST_SUB_COLOR: '#DDB8CF',
  SECOND_SUB_COLOR: '#50A4C5',
  THIRD_SUB_COLOR: '#A4AFC3',
  FORTH_SUB_COLOR: '#2E699A',
};

export { Color };
