const COLORS = {
  BACKGROUND_COLOR: '#F6E8D8',
  BUTTON_COLOR: '#ABCEEA',
  BORDER_COLOR: '#888888',
  FIRST_SUB_COLOR: '#DDB8CF',
  SECOND_SUB_COLOR: '#50A4C5',
  THIRD_SUB_COLOR: '#A4AFC3',
  FORTH_SUB_COLOR: '#2E699A',
  LABEL_COLOR: '#888888',
  BOTTOM_TAB_GALLERY_COLOR: '#EEB7B4',
  BOTTOM_TAB_SETTINGS_COLOR: '#F2CFA5',
  BOTTOM_TAB_ACTIVE_COLOR: '#FDFFFD',
  BOTTOM_TAB_INACTIVE_COLOR: '#A3C2FF',
};

export { COLORS };
